name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Main
      - QA
      - Dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Main

env:
    BUILD_COMMAND: ""

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set env to Dev
        if: endsWith(github.ref, '/Dev')
        run: |
            echo BUILD_COMMAND=':Dev' >> $GITHUB_ENV
      - name: Set env to QA
        if: endsWith(github.ref, '/QA')
        run: |
              echo BUILD_COMMAND=':QA' >> $GITHUB_ENV
      - name: Set env to Production
        if: endsWith(github.ref, '/Main')
        run: |
             echo BUILD_COMMAND='' >> $GITHUB_ENV
      - name: Check env var
        run: |
                echo ${{ env.BUILD_COMMAND }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          production_branch: "Main"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_WAVE_05E78CF1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/make-it-stripe/browser" # Built app content directory - optional
          app_build_command: "npm run build${{env.BUILD_COMMAND}}"
          ###### End of Repository/Build Configurations ######
        env:  # Put a node version on the following line
          NODE_VERSION: 20.9.0
          BRANCH_NAME: ${{github.ref_name }}
          MSBUILD_CONFIGURATION: ${{github.ref_name }}
          RUN_BUILD_COMMAND: "npm run build${{env.BUILD_COMMAND}}"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_WAVE_05E78CF1E }}
          action: "close"
